name             'shell_preferences'
maintainer       'github@jamesjj.net'
maintainer_email 'github@jamesjj.net'
license          'MIT'
description      'Installs/Configures VIM and bash profile'
long_description      'Installs/Configures VIM and bash profile'
version          '0.1.3'
