name             'shell_preferences'
maintainer       'JamesJJ'
maintainer_email 'JamesJJ@users.noreply.github.com'
license          'MIT'
description      'Installs/Configures VIM and bash profile'
long_description      'Installs/Configures VIM and bash profile'
version          '0.1.4'
